services:
  postgres:
    image: postgres:16.4-alpine
    ports:
      - "5432:5432"
    volumes:
      - boilerplate-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  maildev:
    build:
      context: .
      dockerfile: maildev.Dockerfile
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - app-network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

  init-db:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_TYPE=postgres
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=postgres
      - DATABASE_SYNCHRONIZE=false # We run migrations explicitly, so no need for synchronize on startup
      - DATABASE_SSL_ENABLED=false
      - NODE_ENV=development
    command: tail -f /dev/null
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:3000"
    depends_on:
      init-db:
        condition: service_completed_successfully
    environment:
      - DATABASE_TYPE=postgres
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=postgres
      - DATABASE_SYNCHRONIZE=false
      - DATABASE_SSL_ENABLED=false
      - NODE_ENV=development
    command: npm run start:dev
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  boilerplate-db:
